# Generated by Django 2.2.16 on 2022-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='units_measurement',
        ),
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity of ingredients'),
            preserve_default=False,
        ),
    ]
