# Generated by Django 2.2.16 on 2022-04-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20220425_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='units_measurement',
            field=models.CharField(default='g', max_length=50, verbose_name='Units of measurement'),
            preserve_default=False,
        ),
    ]
