# Generated by Django 2.2.16 on 2022-04-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20220418_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='hex',
            new_name='color',
        ),
    ]
