# Generated by Django 2.2.16 on 2022-04-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_ingredient_units_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=5, null=True, verbose_name='Статус'),
        ),
    ]
