# Generated by Django 2.2.16 on 2022-04-19 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Ingredients',
            field=models.ManyToManyField(related_name='recipes', to='recipe.Ingredient', verbose_name='Ingredients for recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipe.Tag', verbose_name='Tag'),
        ),
    ]
